export const EventTypes = {
  ADD_TRANSACTION_INTO_CATEGORY: "ADD_TRANSACTION_INTO_CATEGORY",
  UPDATED_BUDGET: "UPDATED_BUDGET",
  UPDATE_AFTER_CREATE_BUDGET: "UPDATE_AFTER_CREATE_BUDGET",
  CREATE_CATEGORY: "CREATE_CATEGORY",
} as const;
