export const EventTypes = {
  ADD_TRANSACTION_INTO_CATEGORY: "ADD_TRANSACTION_INTO_CATEGORY",
  UPDATED_BUDGET: "UPDATED_BUDGET",
  UPDATE_AFTER_CREATE_BUDGET: "UPDATE_AFTER_CREATE_BUDGET",
  CREATE_CATEGORY: "CREATE_CATEGORY",
  UPDATE_CATEGORY: "UPDATE_CATEGORY",
  DELETE_TRANSACTION_FROM_CATEGORY: "DELETE_TRANSACTION_FROM_CATEGORY", 
  DELETE_CATEGORIES: "DELETE_CATEGORIES"
} as const;
