export const EventTypes = {
  ADD_TRANSACTION_INTO_CATEGORY : "ADD_TRANSACTION_INTO_CATEGORY",
  UPDATED_BUDGET : "UPDATED_BUDGET",
  CREATE_BUDGET : "CREATE_BUDGET",
  CREATE_CATEGORY : "CREATE_CATEGORY"
} as const; 
